#!/bin/bash

# Function to display section headers
print_section() {
    echo "---------------------"
    echo "$1"
    echo "---------------------"
}

# Function to display hardware information
print_hardware() {
    echo "CPU:"
    cat /proc/cpuinfo | grep "model name" | head -n 1 | awk -F': ' '{print $2}'
    
    echo "Speed:"
    lshw -class processor | awk '/description: CPU/{p=1} p && /size:/{print $2; exit}'
    lshw -class processor | awk '/description: CPU/{p=1} p && /capacity:/{print $2; exit}'
    
    echo "RAM:"
    grep -i 'system memory' /proc/meminfo | awk '{print $2}'
    
    echo "Disks:"
    lsblk -o NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6}'
    
    echo "Video card:"
    lspci | grep -i "VGA" | awk -F': ' '{print $2}' | uniq
}

# Function to display network information
print_network() {
    echo "FQDN: $(hostname -f)"
    echo "Host Address: $(hostname -I)"
    echo "Gateway IP: $(ip route | awk '/default/ {print $3}')"
    
    echo "DNS Server:"
    grep "nameserver" /etc/resolv.conf | awk '{print $2}'
    
    echo "Network Interface Information:"
    lshw -class network | grep -E 'description|product|vendor|physical id|logical name' | awk -F ':' '{print $1 ": " $2}'
    
    echo "IP Address:"
    ip -o addr show | awk '$3 == "inet" {print $4}'
}

# Function to display system status
print_system_status() {
    echo "Users Logged In:"
    who | awk '{print $1}' | sort | uniq | paste -s -d ','

    echo "Disk Space:"
    df -h
    
    echo "Process Count:"
    ps -e | wc -l
    
    echo "Load Averages:"
    uptime | awk -F'[a-z]:' '{print $2}'
    
    echo "Memory Allocation:"
    free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}'
    
    echo "Listening Network Ports:"
    ss -tuln | awk 'BEGIN {print "State\tRecv-Q\tSend-Q\tLocal Address:Port\tPeer Address:Port"} /LISTEN/ {print $1 "\t" $2 "\t" $3 "\t" $4 "\t\t" $5}'
    
    echo "UFW Rules:"
    ufw status numbered | grep -v 'Status: active'
}

# Main part of the script
system_report="System Report generated by $(whoami), $(date)"

print_section "System Report"
echo "$system_report"

print_section "System Information"
echo "Hostname: $(hostname)"
echo "OS: $(source /etc/os-release && echo $PRETTY_NAME)"
echo "Uptime: $(uptime -p)"

print_section "Hardware Information"
print_hardware

print_section "Network Information"
print_network

print_section "System Status"
print_system_status

print_section "End of Report"
